[package]
name = "dialoguemaker/dialogue-server-types"
version = "0.1.0-patch-1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/DialogueMaker/dialogue-server-types"
authors = ["Christian Toney <christian.toney@beastslash.com>"]
include = ["src", "src/**/*.lua", "wally.toml", "default.project.json"]
exclude = ["**"]

[dependencies]
dialogue-types = "dialoguemaker/dialogue-types@0.1.0-patch-2"